### ISSUE TITLE
mas api key kelihatan tolong dihapus udah aku dm discord

### ISSUE THREAD

**Issue by uratmangun** [adexaja/carisolusi#1]
https://github.com/adexaja/carisolusi/blob/main/src/components/form-input.tsx#L46 hati2

**Comment by adexaja** [comment]
Oke mas thankyou mas

**Comment by adexaja** [comment]
Solved on commit https://github.com/adexaja/carisolusi/commit/013d7d0da3bcb94ea1e8dcd8d82addd2b35d7a71

Thanks for contribution mas @koisose
